// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqpjgziaxbibsplizqlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxcGpnemlheGJpYnNwbGl6cWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3Mzc0OTUsImV4cCI6MjA1ODMxMzQ5NX0.RHR3LMLAOeFeKtbGgSksln6QfCYiB0m-MSuk0PDI7dY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);